"""100 movie-inspired workplace-escalation scenarios (concepts 131-230).

Theme: people who can't stand their 9-to-5, drawn from 1990s / early-2000s films.
Each entry: (title, inspired_by, start, workplace, carnival, apocalypse)

Rules for turning these into image prompts:
  - `inspired_by` is a reference note only. Never put a film title, character,
    actor likeness, quote, logo or recognisable prop design into an image prompt.
  - The people stay off-screen, as in the other Kari sets. Show their frustration
    through what they leave behind: an empty chair still spinning, a jacket over
    a chair, a half-eaten lunch, a desk mid-pack.
"""

IDEAS = [
# --- Cubicle rebellion ---------------------------------------------------------
("Cover-sheet memo", "Office Space (1999)",
 "A single report on a desk with a missing cover sheet and one memo clipped to it.",
 "Duplicate reminder memos arrive by tube, by tray and by pin, each clipping to the report until it is buried in identical memos.",
 "A carousel of identical memos riding wooden-style frosted horses around the report on a pole.",
 "A drift of memos entombs a ruined cubicle row; a lime binder clamps the single report with its cover sheet."),
("Exiled stapler", "Office Space (1999)",
 "A lime stapler on a tidy desk, its place outlined on the blotter.",
 "The stapler is moved desk by desk down a corridor, then down a stairwell into a dim basement storage room.",
 "A descending spiral slide carrying the stapler down past every floor into the basement.",
 "A flooded basement ruin full of relocated desk objects; a lime lift carries the stapler back up."),
("Printer taken to the field", "Office Space (1999)",
 "A printer on a stand showing a paper-jam error light, one crumpled sheet in its tray.",
 "The printer is wheeled out of the office on a cart, across a car park and into an open grass field.",
 "A strongman high-striker attraction where the printer sits on the target plate under the hammer.",
 "Printer fragments scattered across a scorched field; a lime repair rig reassembles a working paper path."),
("Flair quota", "Office Space (1999)",
 "A uniform on a hanger with a few round pin badges fixed to its strap.",
 "More pins are demanded; the strap fills, then the sleeves, until the uniform sags under the metal.",
 "A pin-badge prize wheel that spins and adds another pin on every turn.",
 "A heap of loose pins around a collapsed wheel; a lime magnet lifts them into one small tray."),
("Saturday request", "Office Space (1999)",
 "A weekend calendar page with a single sticky request slip on Saturday.",
 "Slips spread to Sunday, then across the next weekend and the one after, covering every rest day.",
 "A Ferris wheel whose every gondola is a weekend page, each boarding another slip.",
 "A ruined calendar Ferris wheel fallen across a quiet town; a lime lock seals the weekend gondolas."),
("Lane-switch commute", "Office Space (1999)",
 "A miniature highway model with two lanes of tiny cars and one car switching lanes.",
 "Every lane change lands in the slower lane; the switching car ends up further behind.",
 "A slot-car racing track where one car keeps swapping into whichever lane just stopped.",
 "A cracked highway ruin with cars stalled in both lanes; a lime express lane opens down the middle."),
("Desk to storage B", "Office Space (1999)",
 "A single cubicle near a window, its nameplate blank and its chair tucked in.",
 "The cubicle is shrunk, moved, shrunk again and pushed deeper into the building until it sits beside the boiler room.",
 "A funhouse corridor that narrows at every turn until the cubicle barely fits.",
 "A cubicle half-buried in basement rubble; a lime light rig pushes up through the ceiling."),
("Efficiency consultants", "Office Space (1999)",
 "A clipboard audit form on an interview table with two empty chairs facing one.",
 "The questions multiply; audit forms stack; desks get tagged for removal one by one.",
 "A carnival guess-your-weight scale weighing each desk and printing a tag.",
 "A tagged-desk graveyard across a plain; a lime sorter returns the useful desks to service."),
("Insomnia copier", "Fight Club (1999)",
 "A copier producing one crisp copy of a document.",
 "Copies are made of copies through the night, each fainter and grainier until the stack is mostly grey.",
 "A copier-shaped tilt-a-whirl flinging ever-fainter copies from its cars.",
 "A grey dune of illegible copies under night light; a lime scanner recovers the original."),
("Catalogue apartment", "Fight Club (1999)",
 "A tidy flat-pack furniture box on a studio floor, an office badge on top.",
 "The room fills with identical catalogue furniture until it's more showroom than home, the badge lost beneath.",
 "A showroom-maze attraction of identical rooms with numbered arrows on the floor.",
 "A collapsed showroom ruin; a lime path clears one real room in the middle."),
("Single-serving travel", "Fight Club (1999)",
 "A tray table with a single-portion meal, a tiny soap and a boarding stub.",
 "Single-use portions multiply per trip until the tray table overflows with tiny packages.",
 "A conveyor-belt sushi ride where every plate is another single-serving portion.",
 "A landfill of tiny portions around a ruined conveyor; a lime compactor sorts them."),
("Recall formula", "Fight Club (1999)",
 "A brass balance scale with one small car model on one pan and a thin stack of claim forms on the other.",
 "Claim forms keep landing on the pan; instead of fixing the car, the scale is recalibrated again and again while cars queue behind it.",
 "A seesaw ride that tips cars against towers of claim forms, never settling level.",
 "A snapped scale in a scrapyard of cars and paper; a lime lever re-seats the beam and levels it."),
("Drive-thru downshift", "American Beauty (1999)",
 "A leather briefcase leaning against a tiny drive-thru window model, a paper headset beside it.",
 "The briefcase is set aside; order slips stream through the window and a car queue wraps around the building.",
 "A kiddie train of tiny cars circling a drive-thru booth, looping past the window forever.",
 "A cracked, empty drive-thru lot at dusk; a lime lane marking peels off toward open road."),
("Two lines lit", "Jerry Maguire (1996)",
 "A desk phone with two line buttons, one glowing lime.",
 "The second line lights, then extension phones stack on the desk, every line glowing and every receiver off its cradle.",
 "A switchboard-themed bumper-car arena where each car is a ringing handset.",
 "A quiet field of dead handsets around a collapsed switchboard; a lime line reconnects one call."),
("Locked leads", "Glengarry Glen Ross (1992)",
 "A locked drawer of index cards beside a cold desk phone on a rainy-night desk.",
 "Every desk waits on the drawer; phones pile up untouched while the lock stays shut.",
 "A carnival lock-box game with the cards displayed behind glass, just out of reach.",
 "A broken lock-box ruin under grey rain; a lime key finally turns in the drawer."),
("Sales leaderboard", "Glengarry Glen Ross (1992)",
 "A wall leaderboard of blank graphite bars, one lime bar slightly ahead.",
 "The bars race each other up the wall, bend, jam into the ceiling and start pulling the board off its mounts.",
 "A mechanical horse-race arcade game where the bars are the racing lanes.",
 "Fallen bars across a ruined sales floor; a lime scale lays them side by side evenly."),
("Locked coffee", "Glengarry Glen Ross (1992)",
 "A coffee pot behind a small locked glass cabinet door.",
 "Empty mugs queue in front of the cabinet, row after row, while the pot stays sealed.",
 "A claw machine with a single coffee pot as the only prize.",
 "A dry pot in a dusty cabinet among mug shards; a lime tap reopens the flow."),
("Fluorescent hum", "Joe Versus the Volcano (1990)",
 "A long grey corridor model with one flickering fluorescent tube.",
 "Every tube starts flickering in turn; the corridor stretches into the distance, greyer with each fixture.",
 "A dark-ride tunnel lined with flickering light tubes and a slow car moving through.",
 "A dim grey ruin of fallen light fixtures; a single lime lamp lights a path out."),
("Half-height floor", "Being John Malkovich (1999)",
 "An office floor model with a ceiling at half height, a desk hunched beneath it.",
 "The ceiling sinks further; chairs fold, file cabinets tip, and the room compresses.",
 "A crawl-space funhouse where the ceiling lowers as cars pass beneath.",
 "A crushed floor between two intact storeys; a lime jack lifts the ceiling back up."),
("Scripted commute", "The Truman Show (1998)",
 "A perfect miniature cul-de-sac with one car leaving a driveway, a briefcase on its roof rack.",
 "Every element repeats on cue: the same newspaper, the same revolving door, the same desk, and the loop tightens.",
 "A model-town dark ride running on fixed rails past the same scenes every lap.",
 "A cracked painted-sky dome over a model town; a lime door opens in the horizon."),
("Mailroom deluge", "The Hudsucker Proxy (1994)",
 "One parcel on a sorting table in a cavernous mailroom.",
 "Parcels and letters flood down chutes faster than any sorting arm can move, burying the table.",
 "A mailroom helter-skelter where parcels spiral down a slide from the executive floors.",
 "A parcel landslide filling a vast hall; a lime sorting chute restores lanes."),
("Called in on a day off", "Clerks (1994)",
 "A shop shutter half raised, a day-off calendar page pinned beside it.",
 "The shutter jams at half height; shift tasks spill under it and pile around the calendar page.",
 "A shop-front shooting gallery where the shutter drops on every target.",
 "A jammed shutter in a ruined parade of shops; a lime crank lifts it."),
("Rental drop-box overflow", "Clerks (1994)",
 "A return drop-box at a shop door with one tape case in the slot.",
 "Returns overflow the box and spill across the pavement, cases cracking open.",
 "A coin-pusher machine packed with tape cases edging toward the drop.",
 "A drift of cases outside a shuttered store; a lime conveyor sorts them back to shelves."),
("Impossible sweetener", "Swimming with Sharks (1994)",
 "A single coffee cup on a saucer beside one specific sweetener packet.",
 "Wrong packets are rejected one by one; cups multiply along the desk while the right packet can't be found.",
 "A shell game with coffee cups sliding around a table.",
 "A spill of cups and packets across a ruin; a lime tray holds the one correct packet."),
("Late-night book delivery", "The Devil Wears Prada (2006)",
 "A bound mock-up book at the foot of a townhouse staircase at night.",
 "The staircase lengthens with each step; the book gets heavier and more pages are added.",
 "A staircase escalator ride that keeps adding steps.",
 "A collapsed staircase in a quiet street; a lime lift carries the book to the door."),
("Coffee-run relay", "The Devil Wears Prada (2006)",
 "A cardboard coffee tray holding one cup, steam rising.",
 "The order grows to stacks of trays; cups go cold waiting and the tray stack sways.",
 "A spinning teacup ride of takeaway cups whirling past a counter.",
 "A spilled coffee delta across a city block; a lime tray rescues one warm cup."),
("Autopilot remote", "Click (2006)",
 "A universal remote resting beside a desk calendar.",
 "The remote fast-forwards the calendar; pages fly off in a blur and the desk ages around it.",
 "A fast-forward roller coaster with blurred calendar pages streaming alongside.",
 "A desk buried under dust and pages in a faded ruin; a lime pause key stops the drift."),
("Say yes to everything", "Bruce Almighty (2003)",
 "An inbox tray holding a single request slip.",
 "An auto-approve stamp says yes to every slip; approvals blizzard out of the tray and fill the room.",
 "A slot machine that pays out approval tokens on every pull.",
 "An avalanche of approval tokens over a city; a lime filter lets only a few pass."),
("Stopwatch logistics", "Cast Away (2000)",
 "A stopwatch strapped to one parcel on a sorting belt.",
 "Every parcel gets its own stopwatch; the belt speeds up until parcels fly off the end.",
 "A conveyor race track where parcels compete against lap timers.",
 "Parcels washed up on a deserted beach ruin; a lime raft carries one home."),
("Door vault conveyor", "Monsters, Inc. (2001)",
 "One plain door clicking into a tall vault rack on a rail.",
 "The rack speeds up; doors jam, swing open and pile up on the rails.",
 "A door-conveyor roller coaster weaving through a vault of racks.",
 "A collapsed vault of scattered doors; a lime rack reorders them."),
("File your paperwork", "Monsters, Inc. (2001)",
 "A clipboard of paperwork on a service counter with a small window.",
 "Paperwork piles on the counter while the window stays shut; a queue of clipboards forms.",
 "A paper-chute log flume where clipboards splash down.",
 "A paper dune around a ruined counter; a lime filing arm starts filing."),
("Quota canister", "Monsters, Inc. (2001)",
 "A glass canister with a daily-quota gauge, nearly empty.",
 "The canister never fills; more canisters line up, each lower than the last.",
 "A strength-tester booth measuring canisters on a sliding gauge.",
 "Empty canisters across a ruin; a lime gauge fills one to the line."),
("Production line escape", "Chicken Run (2000)",
 "A small conveyor production line with a single hatch.",
 "The line speeds up; product jams at the hatch and backs up the belts.",
 "A factory-machine coaster whose track runs through the production line.",
 "A jammed factory ruin at dawn; a lime gate opens onto a field."),
("Tunnel conformity", "Antz (1998)",
 "An identical row of shovels at identical stations.",
 "Tunnels branch in perfect copies; one tunnel breaks the pattern and the rest start caving in.",
 "A burrowing coaster weaving through identical tunnels.",
 "A collapsed tunnel colony under a meadow; a lime shaft lifts toward the light."),
("Forms in triplicate", "Men in Black (1997)",
 "A form with two carbon copies beneath it on a clipboard.",
 "Carbons multiply; every form spawns three more until the stack towers overhead.",
 "A form-stacking tower game that wobbles with each new layer.",
 "A form dune across a bureaucratic ruin; a lime binder clamps one copy."),
("Files inside the computer", "Zoolander (2001)",
 "A beige computer tower beside a file folder on a desk.",
 "Nobody can find the files; the tower is opened, then dismantled piece by piece across the desk.",
 "A strongman smash booth where the tower sits under the hammer.",
 "Computer shards spread across a plain; a lime drive glows with the files intact."),
("Door falls off the car", "Tommy Boy (1995)",
 "A sales sample case on the seat of a small old car.",
 "A door drops off; samples spill along the road as the car keeps driving.",
 "A bumper-car sales route where cars shed doors at every bump.",
 "A roadside ruin of parts and samples; a lime tow hitch drags the car back."),
("Cold-call phone bank", "Boiler Room (2000)",
 "A single phone on a bare desk in a large open room.",
 "Phones multiply into a trading floor of handsets, all ringing, stacked on every surface.",
 "A merry-go-round of ringing handsets.",
 "A silent floor of dead handsets; a lime line connects one call."),
("Save the shop", "Empire Records (1995)",
 "A small shop counter with a till and a rent notice.",
 "Rent notices pile on the counter until it sinks.",
 "A spinning record ride with the counter at its centre.",
 "A shuttered shop ruin; a lime key reopens the door."),
("Box on the way out", "Reality Bites (1994)",
 "A cardboard box on a desk beside a studio badge.",
 "Belongings are boxed and the box is carried down a long corridor.",
 "A studio-set dark ride past dismantled sets.",
 "A dim studio ruin; a lime spotlight picks out the box."),
("Temp supply mystery", "Clockwatchers (1997)",
 "A stocked supply shelf beside a small temp desk with a visitor badge on it.",
 "Items vanish from the shelf one by one; desk drawers lock and small lamps angle toward the temp desk.",
 "A shell-game booth where supplies are hidden under frosted cups and never under the chosen one.",
 "An emptied, dust-covered shelving ruin; a lime inventory scanner sweeps the aisle and finds the stash."),
("Plaque race", "Employee of the Month (2006)",
 "A long big-box store aisle with one empty wall-plaque frame at the end.",
 "Carts race down the aisle, knocking stock off shelves as more and more empty frames appear on the wall.",
 "A shopping-cart roller coaster racing through towering aisles toward a single frame.",
 "A collapsed aisle of fallen shelving and dented carts; a lime cart rolls clear with the frame."),
("Pudding loophole", "Punch-Drunk Love (2002)",
 "One pudding cup on a stockroom shelf beside a clipped coupon.",
 "Pudding cups are bought and stacked until they fill the stockroom and roll out into the warehouse aisles.",
 "A carnival ball-toss booth built from stacked pudding-cup pyramids.",
 "A dune of pudding cups across a warehouse ruin; a lime pallet jack hauls one tidy pallet away."),
("Honesty in the meeting", "Liar Liar (1997)",
 "A polished meeting table with one agenda sheet and one pen.",
 "Each blunt answer tips something over; papers slide, chairs roll back and the agenda sheet tears.",
 "A truth-tester booth with a swinging needle that sends a bell up a tower each time.",
 "A boardroom ruin with a split table; one lime chair stands upright at its head."),
("Eight-to-noon window", "The Cable Guy (1996)",
 "A wall clock with a lime arc from eight to twelve beside a front door.",
 "The arc stretches past noon and round again; waiting chairs line up down the hallway.",
 "A waiting-room carousel of empty chairs circling the front door.",
 "A clock fallen across a ruined hallway; a lime door finally swings open."),
("Auto-layoff machine", "Idiocracy (2006)",
 "A row of desks with a slim automated evaluation box on each one.",
 "The boxes flag desks automatically; flagged desks are ejected out of the row on rails.",
 "A circus cannon firing desks across the big top into a net.",
 "A field of ejected desks around a burnt-out control box; a lime rig restores one row."),
("Stock goes to zero", "Fun with Dick and Jane (2005)",
 "A brass stock gauge on an executive desk, its lime needle high.",
 "The needle drops; furniture is carted out, lamps switched off, the office emptied around the gauge.",
 "A drop-tower ride whose car is tied to the falling needle.",
 "An empty office ruin with the gauge on the floor; a lime needle starts to lift."),
("Unpaid internship", "The Pursuit of Happyness (2006)",
 "A briefcase beside a heavy medical-equipment case at a bus stop.",
 "The case gets heavier every stop; the commute route stretches across the city.",
 "A cable-car ride that carries the case up a steep hill and back down.",
 "A dim city ruin on a hillside; a lime tram carries the case to the top."),
("Wiped project memory", "Paycheck (2003)",
 "A small envelope of random personal items on a desk.",
 "The items don't explain the project; the desk fills with unexplained objects and unanswered notes.",
 "A memory-lane dark ride through rooms of unexplained objects.",
 "A dim ruin of scattered objects; a lime thread links them in order."),
("Erase the bad project", "Eternal Sunshine of the Spotless Mind (2004)",
 "A project folder on a desk under a lamp.",
 "The desk, then the room, begins to dissolve at the edges as the project is erased piece by piece.",
 "A dark ride whose sets dissolve as each car passes.",
 "A ruin with blurred, missing edges; a lime outline redraws the room."),
("Jet-lagged work trip", "Lost in Translation (2003)",
 "A hotel-room desk with a laptop and a bedside clock at 3 a.m.",
 "Clocks multiply across the desk, each showing a different time, and the city lights outside blur.",
 "A night-city Ferris wheel whose gondolas are hotel rooms.",
 "A dim skyline ruin; a lime clock settles on one time."),
("Corporate gym", "Dodgeball (2004)",
 "A treadmill positioned beside an office desk.",
 "Desks are pulled onto treadmills, then onto rowing machines, until work happens only in motion.",
 "A dodgeball booth hurling desk items across a gym floor.",
 "A gym ruin with fallen equipment; a lime bench stands clear."),
("Teleprompter runaway", "Anchorman (2004)",
 "A teleprompter showing blank grey lines.",
 "The prompter scrolls faster and faster; scripts spill off the rollers.",
 "A newsroom carousel spinning scripts on its poles.",
 "A studio ruin buried in script paper; a lime prompter scrolls at a steady pace."),
("Concession overflow", "Ghost World (2001)",
 "A cinema concession stand with a popcorn machine.",
 "Popcorn overflows the kettle, the counter and then the lobby.",
 "A popcorn-machine ride where the kettle is the car.",
 "A popcorn dune over a ruined lobby; a lime scoop clears a path."),
("Billable hours", "The Firm (1993)",
 "A time card on a mahogany law desk.",
 "Time cards stack on the desk until it sinks into the floor under their weight.",
 "A clock-punch booth stamping cards on a conveyor.",
 "A time-card dune around a sunken desk; a lime punch clock resets."),
("Cloned yourself", "Multiplicity (1996)",
 "One desk with one chair and one coffee mug.",
 "Copies of the desk appear side by side, each slightly worse than the last copy.",
 "A copy-of-a-copy carousel of increasingly warped desks.",
 "A ruin of degraded desk copies; a lime frame keeps only the original."),
("Undercoat upsell", "Fargo (1996)",
 "A car-lot sales desk with a single add-on form.",
 "Add-on forms stack onto every sale until the paperwork outweighs the car.",
 "A car-lot bumper-car arena with add-on forms trailing each car.",
 "A snowy car-lot ruin; a lime car drives away with one form."),
("Can't drop below pace", "Speed (1994)",
 "A deadline speedometer on a desk with a lime minimum marker.",
 "The needle can't drop below the marker; every task is done at speed and things fly off the desk.",
 "A bus-shaped roller coaster that can never slow down.",
 "A broken highway ruin; a lime brake finally engages."),
("Systems are down", "Jurassic Park (1993)",
 "A control-room console with one blinking warning lamp.",
 "Systems cascade offline one by one; security doors slide open along a corridor.",
 "A jungle safari ride whose gates have all swung open.",
 "An overgrown control-room ruin; a lime switch reboots the grid."),
("Sinking launch", "Titanic (1997)",
 "A product-launch model riding on a tabletop sea.",
 "The launch lists to one side; lifeboats are cut from the budget one by one.",
 "A pirate-ship swing ride rocking the launch model.",
 "A sunken launch on the sea floor; a lime lifeboat carries the salvage."),
("Booby-trapped office", "Home Alone (1990)",
 "A desk with a single tripwire stretched across a doorway.",
 "The trap triggers another trap, and another, cascading through the office.",
 "A Rube Goldberg funhouse of desk traps.",
 "A trap-strewn office ruin; a lime path clears through it."),
("Square filter, round hole", "Apollo 13 (1995)",
 "A square filter beside a round slot on a console.",
 "Improvised fixes pile up with tape, hoses and binder covers.",
 "A shape-sorter carnival game with the wrong shapes at every slot.",
 "A capsule-like ruin; a lime adapter fits the square into the round."),
("Shifting cube rooms", "Cube (1997)",
 "A single cube-shaped room with hatches on all six sides.",
 "The rooms slide and rotate; every hatch leads to another identical room.",
 "A cube-maze ride that rotates as the car moves.",
 "A stacked cube ruin; a lime hatch opens to the outside."),
("Contract takes your name", "Spirited Away (2001)",
 "A contract sheet on a desk with a nameplate beside it.",
 "The nameplate fades as contracts pile higher.",
 "A bathhouse-style lift ride climbing between floors of contracts.",
 "A misty ruin of contract piles; a lime nameplate glows again."),
("Denied claims cubicle", "The Incredibles (2004)",
 "A cramped cubicle with a single claim form and a rubber stamp.",
 "Every claim is stamped denied; the cubicle walls close in as the stack grows.",
 "A stamp-press carnival game that stamps every card the same.",
 "A crushed cubicle ruin; a lime stamp approves one claim."),
("Task board stampede", "Jumanji (1995)",
 "A board game of task tiles on a desk with a pair of dice.",
 "A roll releases a stampede of task tiles that tramples the office.",
 "A board-game ride where cars move space by space and trigger stampedes.",
 "A trampled office ruin; a lime board resets to start."),
("Thawed and outdated", "Austin Powers: International Man of Mystery (1997)",
 "A cryo-chamber beside a desk with an old beige computer.",
 "The desk thaws decades later, surrounded by equipment it can't plug into.",
 "A time-capsule ride through obsolete office eras.",
 "A ruin of outdated equipment; a lime adapter connects the old to the new."),
("Overqualified at the counter", "High Fidelity (2000)",
 "A record-store counter with a stack of list cards.",
 "Lists pile up; the queue waits; the stack topples.",
 "A spinning-record ride with the counter at its centre.",
 "A record-shop ruin; a lime needle drops on one record."),
("System erased you", "The Net (1995)",
 "An employee file folder on a desk.",
 "The file is erased; the badge stops opening doors, and the desk is cleared.",
 "An identity dark ride where every door refuses to open.",
 "A data-vault ruin; a lime file is restored to the drawer."),
("Daily sample check", "Gattaca (1997)",
 "A sleek entry turnstile with a small sample reader, one lime light waiting at the gate.",
 "Each morning the check gets stricter; a second reader is bolted on, then a third, and the queue of badges snakes back through the lobby.",
 "A turnstile carousel that rotates the badge queue past a chain of readers without ever letting one through.",
 "A turnstile ruin in a vast, clean, abandoned lobby; a lime gate slides open beside the readers."),
("Midnight reorg", "Dark City (1998)",
 "An office floor under a night sky seen through tall windows, desks in neat rows.",
 "At midnight the walls slide, floors rotate and desks rearrange while the lights are off; by morning nothing is where it was.",
 "A shifting-building dark ride where the walls move around the car as it travels.",
 "A tangle of half-rotated floors and misplaced desks under a dark sky; a lime floor plan is laid out and walls lock into place."),
("Daily re-onboarding", "50 First Dates (2004)",
 "An onboarding cassette and a welcome packet waiting on a fresh desk each morning.",
 "Each day starts from the same tape; welcome packets pile up, unread past page one.",
 "A tape-loop carousel where the car rides the same short track every lap.",
 "A shoreline ruin of unspooled tape and welcome packets; a lime cassette ejects with a single saved note."),
("Photo-note handoff", "Memento (2000)",
 "A desk scattered with a few instant-photo notes, each with a blank caption strip.",
 "Context is lost between shifts; photos multiply, contradict each other and cover the walls in overlapping layers.",
 "A photo-booth dark ride whose corridors are papered with instant photos.",
 "A ruin of faded photos drifting across a motel-like courtyard; a lime thread links them in the right order."),
("Seven-day countdown", "The Ring (2002)",
 "A countdown dial on a desk with seven lit segments beside one project folder.",
 "Segments go dark one by one while the folder stays unopened and tasks pile up around it.",
 "A countdown drop tower that ratchets higher as each segment goes dark.",
 "A stone-well-shaped ruin of stacked folders; a lime rope is lowered to lift the project out."),
("Office chain reaction", "Final Destination (2000)",
 "A small desk fan pointed at a loose stack of paper next to a full coffee cup.",
 "One sheet lifts; it tips the cup, which shorts a power strip, which drops a shelf, which topples the next desk in a chain.",
 "A Rube Goldberg coaster where each car sets off the next piece of office mayhem.",
 "A chain of toppled desks and shelves across a wide ruin; a lime stop block halts the last link."),
("Golden ticket line", "Charlie and the Chocolate Factory (2005)",
 "A factory conveyor carrying neatly wrapped bars past a single inspection station.",
 "The line speeds up; wrappers tear and pile; the inspector station is buried in bars.",
 "A river boat ride through a factory with conveyors running overhead.",
 "A silent factory ruin with dried rivers and stopped belts; a lime conveyor restarts one lane."),
("Frozen clock", "Clockstoppers (2002)",
 "An office clock frozen at 4:59, a desk beneath it.",
 "Everything freezes except the task pile on the desk, which keeps growing while the clock refuses to move.",
 "A frozen-time carousel where the animals are paused mid-stride.",
 "A frost-bound office ruin; a lime second hand begins to tick."),
("Road not taken", "The Family Man (2000)",
 "A briefcase beside a toolbox at a fork in a miniature path.",
 "Two versions of the day split down each path, both piling up unfinished.",
 "A split-track coaster where the train divides at the fork.",
 "Two ruined paths across a valley; a lime bridge joins them."),
("Blinking drive", "Hackers (1995)",
 "A server rack with one blinking drive among dark ones.",
 "Drives blink everywhere, faster and faster, and the rack starts to overheat.",
 "A server-rack light-show ride under a big-top canopy.",
 "A cooled server ruin in a dark hall; one lime drive glows steady."),
("Sponsor clutter", "Wayne's World (1992)",
 "A small basement public-access TV set with two chairs and a single contract on the table.",
 "Sponsor products crowd onto the set, stacking on chairs and taping to the backdrop until the set is buried.",
 "A TV-set carousel of spinning product displays.",
 "A basement studio ruin under product rubble; a lime camera pans across one clean chair."),
("Jump-to-conclusions mat", "Office Space (1999)",
 "A floor mat of answer squares beside a desk, one square glowing lime.",
 "Every decision is made by hopping onto a square; decisions pile up in random directions across the floor.",
 "A giant hopscotch ride where cars bounce square to square with no path.",
 "A cracked, scattered mat across a ruin; a lime path shows the one sensible route."),
("Ticket rail overload", "Waiting... (2005)",
 "A restaurant kitchen ticket rail with one order slip clipped to it.",
 "Slips crowd the rail, overlap and spill onto the pass; plates stack under heat lamps.",
 "A spinning ticket-rail Ferris wheel whose gondolas are order slips.",
 "A kitchen ruin under a drift of slips; a lime rail clips them back in order."),
("Clock-tower deadline", "The Hudsucker Proxy (1994)",
 "A giant clock face on an office tower with a lime hand near midnight.",
 "The hand crawls toward the deadline while the floors below fill with unfinished work.",
 "A clock-tower drop ride that falls one floor for each minute.",
 "A snowy tower ruin with a stopped clock; a lime gear restarts it."),
("Airport form loop", "The Terminal (2004)",
 "A departure-gate counter with one stamped form and an empty queue.",
 "The form is rejected again and again; the traveller's belongings stack beside the gate as the days pass.",
 "A baggage-carousel ride circling a gate that never opens.",
 "A sunlit, empty terminal ruin; a lime gate finally lets one form through."),
("Supply closet heist", "Ocean's Eleven (2001)",
 "A locked supply closet with a single request form taped to the door.",
 "The approval process is so slow that a heist-style plan unfolds across a table: blueprints, timers, laser-grid diagrams.",
 "A laser-grid funhouse ride threading through a mock vault.",
 "A dismantled vault ruin; a lime key simply opens the closet."),
("Admin-rights ceiling drop", "Mission: Impossible (1996)",
 "A white server room with one terminal needing a single permission.",
 "Getting the permission requires lowering through the ceiling on cables past sensors and alarms.",
 "A cable-drop ride that lowers cars into a white vault room.",
 "A white room in ruins, ceiling tiles scattered; a lime access card sits in the reader."),
("Paperwork twister", "Twister (1996)",
 "A single loose form on a desk near an open window.",
 "Wind catches the form, then the stack, and a spiralling column of paperwork rises over the office.",
 "A spinning swing ride whose seats are caught in a paper vortex.",
 "A flattened plain strewn with paper after the storm; a lime anemometer spins calm and the forms are collected."),
("Deadline asteroid", "Armageddon (1998)",
 "A small model asteroid hovering over a desk calendar.",
 "The asteroid grows as the deadline approaches; the desk team drills into it.",
 "A space-drill ride descending into an asteroid.",
 "A cratered ruin; a lime drill rig splits the asteroid."),
("Prototype taken for production", "Galaxy Quest (1999)",
 "A cardboard-and-tape prototype on a stand, clearly a mock-up.",
 "The mock-up is treated as the real thing; parts are ordered, stands are built, launch plans form around it.",
 "A space-ship ride built around a cardboard prop.",
 "A collapsed prop ruin; a lime frame builds the real one beside it."),
("Monochrome office", "Pleasantville (1998)",
 "A monochrome grey office with one lime object on a desk.",
 "The grey spreads over every surface; routines repeat in black and white.",
 "A grey carousel with one lime horse.",
 "A grey ruin where lime colour is spreading from one desk."),
("Harvest quota", "A Bug's Life (1998)",
 "A small platform piled with a seasonal quota of grain.",
 "The quota doubles; the platform groans and the grain spills.",
 "A harvest-conveyor ride carrying grain up a tower.",
 "A drought-cracked ruin; a lime conveyor delivers a fair load."),
("Citation quota", "Super Troopers (2001)",
 "A ticket pad on a dashboard with a quota counter.",
 "Tickets are issued for everything until the pad runs empty and the counter spins.",
 "A patrol-car bumper-car arena.",
 "A snowy highway ruin; a lime counter resets."),
("The call you can't leave", "Phone Booth (2002)",
 "A phone booth on a street corner with the receiver off the hook.",
 "Work calls keep the receiver tethered; the booth shrinks around it.",
 "A phone-booth drop tower that won't let go.",
 "A ruined street; a lime cord snaps free."),
("Hospitality-suite vigil", "The Big Kahuna (1999)",
 "A hotel hospitality suite with a tray of snacks and one empty chair for the client.",
 "Hours pass, snacks go stale, the tray empties and refills and the chair stays empty.",
 "A rotating hotel-room carousel.",
 "A dusty suite ruin; a lime chair is filled."),
("Remote volleyball coworker", "Cast Away (2000)",
 "A home desk with a volleyball propped on the chair opposite.",
 "Isolation grows; notes and sticky messages pile around the ball.",
 "A beach-ball carousel.",
 "An island ruin of home-office gear; a lime raft signals a return to the office."),
("Fifteen-minute escape hatch", "Being John Malkovich (1999)",
 "A small hatch behind a filing cabinet with a lime handle.",
 "Tasks queue up in front of it as everyone lines up for fifteen minutes away.",
 "A portal slide dropping cars out of the office for a short loop.",
 "A ruined filing floor; a lime hatch reopens."),
("Dinner-table buzz", "The Devil Wears Prada (2006)",
 "A dinner table set for two with a phone face-down beside the plate.",
 "The phone buzzes, then again; plates cool as work floods in.",
 "A buzzing phone carousel.",
 "A dinner-table ruin; a lime cloth drapes the phone."),
("Dial-up handshake", "You've Got Mail (1998)",
 "A beige modem on a desk beside a tangle-free phone line.",
 "The connection screeches, drops, retries, drops again.",
 "A carnival music-box ride of screeching tones.",
 "A dusty modem ruin; a lime cable finally connects."),
("Forecast board", "The Weather Man (2005)",
 "A weather map on an easel with one lime front line.",
 "The forecast is wrong; debris hits the board.",
 "A weather-vane ride spinning wildly.",
 "A storm-battered ruin; a lime vane points steady."),
("Synergy merger", "In Good Company (2004)",
 "Two small office models side by side, each with its own org blocks.",
 "They're pushed together; blocks overlap and duplicates are ejected.",
 "A two-car coupling coaster.",
 "A merged ruin; a lime frame aligns one chart."),
]
