"""100 new workplace-escalation scenarios (concepts 31-130) for Kari Tech.

Each entry: (title, category, start, workplace, carnival, apocalypse)
  start       - clean, ordinary mechanism with one recognizable annoyance
  workplace   - physical chain reaction; source stays traceable
  carnival    - the broken workflow as a literal ride or midway attraction
  apocalypse  - large-scale ruin; source hard to trace; lime recovery begins
"""

IDEAS = [
# --- Meetings & calendar ---------------------------------------------------
("Meeting overrun hourglass", "Meetings & calendar",
 "A tabletop hourglass beside a row of paper calendar blocks, the lime sand band marking the booked hour.",
 "Sand keeps pouring past the mark, overflows the base and buries the next calendar blocks, shoving the last ones off the table edge.",
 "An hourglass Ferris wheel whose gondolas are calendar blocks that fill with sand and never reach the unloading platform.",
 "A collapsed Ferris wheel half-buried in a grey sand dune; lime sieve conveyors sift hour tokens back out of the drift."),
("Recurring meeting zombie", "Meetings & calendar",
 "A single recurring-invite card on a brass spindle next to an archived project box.",
 "The spindle keeps stamping identical invite cards long after the project box is sealed, stacking them up the wall.",
 "A merry-go-round of identical invite cards circling a sealed project crate, the organ mechanism stuck on repeat.",
 "The carousel has sunk into layers of compressed invite cards like sediment; a lime cutting rig trims the spindle at its root."),
("Time-zone math", "Meetings & calendar",
 "Three small desk clocks set to different hours, one meeting card sliding between them.",
 "The clock hands catch on each other, gears grind, and the meeting card is dragged into the dark overnight slot.",
 "A spinning teacup ride where each cup is a clock face turning at its own speed, the meeting card tossed cup to cup.",
 "Toppled clock towers across a dim plain; a lime gear train is laying a single synchronized drive shaft between them."),
("No-agenda meeting", "Meetings & calendar",
 "A meeting-table model with one blank agenda sheet at its centre.",
 "The table extends, more chairs slot in, and discussion tubes loop from seat to seat without ever reaching the blank sheet.",
 "A circular hedge-style maze ride built of frosted acrylic around the blank sheet, with no exit gate.",
 "An overgrown maze ruin at landscape scale; a lime survey crawler lays one straight track from the centre to the edge."),
("Wrong window screen-share", "Meetings & calendar",
 "A laptop mirroring one tidy window onto a small projector screen.",
 "The beam splits and spills private drafts, half-finished files and open tabs across every wall of the room.",
 "A hall-of-mirrors attraction where each panel reflects another stray window deeper into the maze.",
 "A shattered mirror field stretching to the horizon; lime frames re-seat one clean pane at a time."),
("Frozen video call", "Meetings & calendar",
 "A webcam aimed at a single frosted video tile on a desk stand.",
 "The tile ices over, neighbouring tiles freeze to it, and buffer icicles grow down from the monitor.",
 "An ice-rink carousel where frozen video tiles glide in a stuck loop under a frosted canopy.",
 "A glacier of fused tiles fills a valley; lime heating cables melt a narrow channel through it."),
("Double-booked room", "Meetings & calendar",
 "A single miniature conference room with two booking tabs clipped to the door.",
 "Two full meeting setups push into the same room; tables overlap and the walls bow outward.",
 "A bumper-car arena of conference tables ramming each other inside one small room.",
 "The room shell is crushed flat among wrecked tables; lime rails partition the site into clean bays."),
("Quick call that isn't", "Meetings & calendar",
 "A small fifteen-minute calendar chip on an otherwise open day strip.",
 "The chip stretches like taffy across the whole day strip, pulling lunch and focus blocks along with it.",
 "A midway taffy-pulling machine endlessly stretching one calendar chip across rotating arms.",
 "Hardened taffy flows have set over a miniature office district; lime cutters slice it back into segments."),
("Lost action items", "Meetings & calendar",
 "An open notebook on a meeting table with three action-item cards tucked in.",
 "The cards slip through a gap in the table and fall down a chute into the floor below.",
 "A drop-tower ride where action-item cards plunge from the top and never come back up.",
 "A deep pit of lost cards at the foot of a collapsed tower; a lime retrieval claw lifts them out one by one."),
("Waiting-room limbo", "Meetings & calendar",
 "A tiny virtual waiting-room lobby model with one pending tile at the door.",
 "More pending tiles queue behind it in a stanchion line that snakes off the desk and across the floor.",
 "Amusement-park queue switchbacks that wind forever toward a ride entrance that never opens.",
 "A rusted field of stanchions and sagging ropes; a lime gate finally swings open at the far end."),

# --- Email & messaging -----------------------------------------------------
("Out-of-office loop", "Email & messaging",
 "Two desk mail trays, each with an auto-reply envelope ready to send.",
 "Each tray auto-answers the other, envelopes shuttle back and forth faster and pile up between them.",
 "A tennis-ball-machine attraction volleying envelopes between two launchers across a net.",
 "Drifts of envelopes between two ruined towers; a lime cut-off valve closes the channel between them."),
("CC creep", "Email & messaging",
 "One outgoing envelope with a single delivery tube to one mail slot.",
 "The tube keeps branching to more and more mail slots until the envelope splits into dozens of copies.",
 "A zip-line rig that forks into dozens of lines, each carrying a copy of the same envelope.",
 "A fallen grid of zip lines draped over wreckage; a lime crawler restores a single clean line."),
("Subject-line fork", "Email & messaging",
 "A neat thread of stacked envelopes on a single rail.",
 "One altered envelope switches the rail; the thread splits into parallel tracks that never rejoin.",
 "A roller-coaster junction that splits one train into several branches running in different directions.",
 "Derailed coaster tracks fan across a canyon; a lime switching mechanism rejoins them to one line."),
("@here broadcast", "Email & messaging",
 "A single desk bell on one desk in a grid of quiet desks.",
 "Striking the one bell triggers every bell in the grid, and the vibration rattles work off every desk.",
 "A high-striker attraction whose bell is struck again and again, each hit ringing a tower of smaller bells.",
 "Cracked bells lie scattered across a flattened office plain; lime dampers clamp them silent one by one."),
("Channel sprawl", "Email & messaging",
 "One tidy chat-channel tray with a few message tiles in it.",
 "The tray splits into dozens of near-identical trays, message tiles scattering between them.",
 "A carnival duck-pond game with dozens of identical channel floats circling in a trough.",
 "A dried pond basin with stranded channel floats; a lime sorting flume routes them into a few channels."),
("Draft graveyard", "Email & messaging",
 "An outbox tray with one half-finished envelope resting under the lid.",
 "Unsent drafts accumulate until the outbox lid can no longer close and the tray jams.",
 "A slow log-flume ride where draft envelopes drift but never reach the drop.",
 "A silted, dry flume channel; a lime pump pushes the first draft over the drop."),
("Per my last email", "Email & messaging",
 "A printed email with an older quoted message folded beneath it.",
 "The quote chain nests deeper and deeper; printouts stack inside printouts into a tower.",
 "A nested tunnel ride of ever-smaller frosted arches, each containing the previous message.",
 "Collapsed nested tunnels form a mound; a lime boring rig drills straight to the original message."),
("Accidental send", "Email & messaging",
 "A spring-loaded send lever holding a half-written envelope.",
 "The lever fires early; the envelope launches and recall mechanisms chase it down the table.",
 "A circus cannon firing half-written envelopes across the big top into a net that isn't there.",
 "A crater field studded with launched envelopes; a lime capture net is being strung across it."),
("Unread counter", "Email & messaging",
 "A mechanical counter showing a small unread number beside an inbox tray.",
 "The counter spins faster than it can be read, digits roll over and the drum rattles loose.",
 "A slot-machine midway where every reel is an unread counter spinning without stopping.",
 "Jammed slot machines stand in a silent arcade ruin; a lime reset lever is pulled on the first one."),
("Signature attachment snowdrift", "Email & messaging",
 "An email envelope with two tiny logo-image tiles clipped to it.",
 "Every reply adds more tiny image tiles until a snowdrift of icons buries the thread.",
 "A claw machine packed with tiny icon tiles, the claw grabbing only more icons.",
 "A flattened claw machine in icon rubble; a lime filter screen separates the message from the clutter."),

# --- Files & documents -----------------------------------------------------
("File locked by another user", "Files & documents",
 "A document folder with a small graphite padlock on the clasp.",
 "Waiting copies line up at the lock; more padlocks clamp onto each copy.",
 "A lock-and-key carnival game where rows of padlocks spin on a wheel and no key fits.",
 "A heap of rusted padlocks fused together; a lime master-key rig works its way through."),
("Sync conflict copies", "Files & documents",
 "A frosted cloud-shaped canister syncing one document down a tube.",
 "Two versions collide in the tube and conflicted copies branch off, multiplying down side pipes.",
 "A sky-ride chairlift where each chair drops another duplicate copy onto the ground.",
 "A collapsed chairlift over a field of duplicates; a lime merge press compacts them into one."),
("Request access door", "Files & documents",
 "A document visible behind a frosted glass door with a request slot.",
 "Request slips pile up in the slot and spill across the floor; the door never opens.",
 "A turnstile attraction with a long line of request tokens and a turnstile that never turns.",
 "Buried turnstiles in a drift of request slips; a lime gate mechanism is being installed."),
("Comment pileup", "Files & documents",
 "A draft page on a stand with three small comment flags pinned in the margin.",
 "Comment flags multiply until the page is a pincushion that can no longer be read.",
 "A pinball machine where comment flags are bumpers and the draft page is the ball.",
 "A flattened pinball field studded with flags; lime sweepers resolve and clear a lane."),
("Markup sediment", "Files & documents",
 "A clean page with a single tracked-change strike mark.",
 "Layer after layer of markup overlays stack until the page is a thick translucent block.",
 "A spinning layered-platter ride where each tier is another transparent markup layer.",
 "A sedimentary cliff of markup layers; a lime core drill extracts the clean original."),
("Downloads folder landslide", "Files & documents",
 "A small download tray catching a few files from a chute.",
 "Duplicate downloads pour in faster than the tray can hold and it overflows across the desk.",
 "A ball-pit attraction filled with identical file tokens.",
 "A compacted ball-pit crater; a lime sorter sifts it into labelled bins."),
("Storage full", "Files & documents",
 "A frosted storage canister with a gauge needle near the top.",
 "The canister bursts at the seams and files spray out across the table.",
 "A water-tower splash ride that dumps files on everything below.",
 "A collapsed water tower in a flooded file plain; a lime pipeline routes flow into new tanks."),
("Missing font", "Files & documents",
 "A layout tray of type blocks with one empty slot.",
 "Mismatched substitute blocks are forced in and the press jams, bending the frame.",
 "A letterpress carousel stamping mismatched blank blocks on every rotation.",
 "A shattered press surrounded by scattered type blocks; a lime rack rebuilds the set."),
("Broken slide template", "Files & documents",
 "A small deck of slides on an easel, each element seated in its grid.",
 "Elements drift off the grid slide by slide until they pile in the corners.",
 "A sliding-tile puzzle ride where slide elements shuffle around a grid without solving.",
 "Slide tiles scattered across a wide plain; a lime grid frame re-seats them."),
("Screenshot of a spreadsheet", "Files & documents",
 "A camera on a tripod photographing a printed spreadsheet sheet.",
 "Photos of the photo are taken and passed along, each flatter and less usable than the last.",
 "A photo-booth attraction printing endless strips of flattened tables.",
 "A dune of photo strips; a lime scanner converts the first strip back into live cells."),

# --- Spreadsheets & data ---------------------------------------------------
("Sorted one column", "Spreadsheets & data",
 "A two-column tile tray where each row's tiles are paired by a lime link.",
 "One column is sorted alone; rows slide apart and every pair is mismatched.",
 "A roller-coaster train whose cars have decoupled and run on two separate tracks.",
 "Derailed coaster cars piled in a ravine; a lime coupler reattaches the correct pairs."),
("Filter left on", "Spreadsheets & data",
 "A spreadsheet tray with a small funnel filter clipped to one column.",
 "Filtered rows drop through the floor into a hidden compartment and silently accumulate.",
 "A funhouse with trapdoor floors where rows fall out of sight.",
 "An underground cavern of hidden rows; a lime lift brings them back to the surface."),
("Merged cells", "Spreadsheets & data",
 "A grid of frosted acrylic cells with two merged into one.",
 "Merges spread across the grid until nothing can be sorted or split.",
 "A tilt-a-whirl platform built from fused cells that can only spin as one lump.",
 "A monolithic fused slab across the landscape; a lime saw cuts it back into cells."),
("#REF chain collapse", "Spreadsheets & data",
 "A chain of formula linkage rods connecting cells on a tabletop.",
 "One rod is pulled; the linkage collapses cell by cell down the table.",
 "A Rube Goldberg marble run where one missing piece sends every marble off course.",
 "Scattered rods and marbles across a ruin; a lime linkage rig reconnects the chain."),
("Encoding garbage", "Spreadsheets & data",
 "Clean data tiles feeding into a small converter box.",
 "The converter spits out scrambled, abstract glyph tiles that clog the output tray.",
 "A tombola drum tumbling scrambled tiles.",
 "A mound of scrambled tiles; a lime decoder frame restores them."),
("Date format swap", "Spreadsheets & data",
 "Two flip-panel date stamps side by side.",
 "Day and month panels swap; schedules misfire and paper deadlines tumble.",
 "A giant flip-clock wheel spinning its panels out of order.",
 "Flip panels scattered across a plain; a lime aligner snaps them back into order."),
("Duplicate CRM contacts", "Spreadsheets & data",
 "A small card file of contact cards.",
 "Each card duplicates itself until the drawers burst.",
 "A coin-pusher machine packed with identical contact cards.",
 "Drifts of duplicate cards; a lime dedupe press stacks unique cards."),
("Empty merge field", "Spreadsheets & data",
 "A batch of envelopes on a conveyor, each with an empty bracketed slot.",
 "The batch ships out with blank slots and returns stamped back.",
 "A roller-coaster of envelopes racing past a stamping station that stamps nothing.",
 "Returned envelopes piled around a derailed coaster; a lime stamp fills slots."),
("Attribution tug-of-war", "Spreadsheets & data",
 "One conversion token tied to two channel ropes on a desk.",
 "More ropes attach and pull in every direction until the token tears.",
 "A carnival tug-of-war game with many ropes on a single token.",
 "Snapped ropes over a ruined arena; a lime ledger mechanism splits the token fairly."),
("Stale pivot", "Spreadsheets & data",
 "A pivot-table model with a refresh crank.",
 "The crank is forgotten; the model drifts out of step with the incoming data feed that piles up behind it.",
 "A scrambler ride whose arms swing data blocks around but never reorders them.",
 "A seized scrambler ride half-buried in unprocessed data; a lime crank drive restarts it."),

# --- Tools & tech ----------------------------------------------------------
("Forced update", "Tools & tech",
 "A laptop on a desk with a physical progress bar stand beside it.",
 "The progress bar stalls, rewinds and loops while work piles up next to it.",
 "A loop-the-loop coaster that never exits the loop.",
 "A rusted loop track over a dead desk city; a lime exit track is being welded."),
("VPN drop", "Tools & tech",
 "A frosted acrylic tunnel pipe between a laptop and a server block.",
 "The tunnel keeps collapsing and packets pile up at the breaks.",
 "A tunnel-of-love boat ride where the tunnel keeps caving in.",
 "A caved-in tunnel under a ruin; lime shoring braces the passage."),
("2FA code sprint", "Tools & tech",
 "A code-token device on a shelf across the room from the laptop.",
 "Codes expire before they arrive; tokens pile up mid-route.",
 "A whack-a-mole board where code tokens pop up and vanish.",
 "A cracked mole-board ruin; a lime key fits one hole."),
("Adapter stack", "Tools & tech",
 "A laptop with one port and a single graphite adapter block.",
 "Adapters stack on adapters into a teetering tower.",
 "A stacking-block strongman tower that sways with each new adapter.",
 "Toppled adapter towers in rubble; a lime single hub stands upright."),
("Wi-Fi dead zone", "Tools & tech",
 "A router with frosted signal rings spreading over a desk grid.",
 "A dead zone grows; rings break and desks fall dark.",
 "A ring-toss game where signal rings miss every desk peg.",
 "Scattered rings over a dark plain; lime repeaters relight a path."),
("Subscription sprawl", "Tools & tech",
 "One subscription card in a small holder.",
 "Cards multiply and a billing conveyor starts feeding them out endlessly.",
 "A ticket-booth attraction spooling out endless ticket rolls.",
 "Ticket drifts across a ruined midway; a lime consolidator winds them into one roll."),
("Broken integration", "Tools & tech",
 "Two gear systems linked by one lime coupling.",
 "The coupling snaps; each gear system spins on its own, throwing work off.",
 "A gear-driven ride where the two halves detach and spin apart.",
 "Two gear ruins facing each other across a gap; a lime coupling bridges them."),
("Retry storm", "Tools & tech",
 "A message cube fired down a chute to a receiving tray.",
 "The receiver doesn't answer; retries multiply until cubes jam the chute.",
 "A batting-cage pitching machine firing cubes nonstop.",
 "A heap of cubes around a toppled pitching machine; a lime backoff valve meters flow."),
("Battery death", "Tools & tech",
 "A laptop with a battery gauge falling toward empty.",
 "The laptop dies mid-task; chargers are hunted across the office, leaving work half-done.",
 "An electric bumper-car rink where every car stalls mid-rink.",
 "Dead cars across a rink ruin; a lime charging grid powers the first car back up."),
("License seats full", "Tools & tech",
 "A rack of seat tokens, every slot full, one token waiting.",
 "Waiting tokens queue, and seats are pried loose to make room.",
 "A carousel with fewer seats than tokens waiting to ride.",
 "A collapsed carousel ringed by waiting tokens; a lime rack adds seats."),

# --- Agency & client work --------------------------------------------------
("Make the logo bigger", "Agency & client work",
 "A tidy ivory layout board with a small graphite mark block in one corner and content blocks seated on a lime grid.",
 "The mark block swells in steps, shoving headline and image blocks to the edges until they topple off the board.",
 "An inflatable bounce house shaped like the swelling mark block, inflating until it crowds every other booth off the midway.",
 "A deflated bounce house draped over flattened layout blocks across a wide plain; a lime grid frame is lowered to restore proportion."),
("Brief ping-pong", "Agency & client work",
 "A single brief sheet resting between two graphite in-trays on a desk.",
 "The brief shuttles between the trays, collecting clipped notes on every pass until the stack is too heavy to land in either.",
 "A pirate-ship pendulum ride swinging the growing brief stack between two tray-shaped platforms.",
 "The pendulum ship lies broken between two ruined platforms buried in clipped notes; a lime anchor pins the brief to one tray."),
("Proofing rounds", "Agency & client work",
 "A proof sheet under a small graphite stamp press with a mechanical round counter.",
 "The counter ticks up each round and a new proof slides out; proofs stack in a leaning column beside the press.",
 "A round-up ride spinning proof sheets against its walls faster with every round.",
 "A mountain of proofs around a seized round-up ride; a lime final-stamp arm descends on the top sheet."),
("Stock photo licensing", "Agency & client work",
 "Three small photo prints on a rail, each with a lime licence tag tied on a string.",
 "Strings tangle and tags drop off as more prints are added; untagged prints spill across the table.",
 "A carnival prize wall of photo prints with licence tags dangling loose beneath each one.",
 "A collapsed prize wall in a field of loose prints; a lime ledger rail threads tags back onto their prints."),
("Colour mismatch", "Agency & client work",
 "A glowing screen swatch beside a printed paper swatch, slightly off in tone.",
 "Each print copied from the last drifts further in tone; a stack of increasingly wrong swatches fans across the desk.",
 "A spinning colour-wheel ride whose segments are all slightly out of true, wobbling as it turns.",
 "A shattered colour wheel spread across a grey basin; a lime calibration rig realigns the first segment."),
("File too big to send", "Agency & client work",
 "An oversized graphite file crate in front of a narrow mail slot.",
 "The crate wedges in the slot, splits, and its chunks scatter down the chute unevenly.",
 "A squeeze-tunnel funhouse where file crates wedge in narrowing frosted passages.",
 "Crate fragments piled at a collapsed tunnel mouth; a lime conveyor widens the passage."),
("Expired transfer link", "Agency & client work",
 "A pneumatic courier tube carrying one file cartridge, a small countdown dial on the tube.",
 "The dial runs out mid-route; cartridges drop from the tubes onto the floor.",
 "A pneumatic-tube ride where cartridges race a countdown dial and fall when it expires.",
 "Broken tube ruins with cartridges scattered beneath them; a lime tube is reconnected across the gap."),
("Ad size explosion", "Agency & client work",
 "One finished ad frame on a small easel.",
 "One small change must be repeated across dozens of frame sizes that fan out around the easel.",
 "A shooting-gallery conveyor of ad frames in every size sliding past in endless rows.",
 "Stacks of mismatched frames fill a ruined gallery; a lime resizing rig works through them one by one."),
("Tracking tag chaos", "Agency & client work",
 "Link tokens with neat lime tags entering one clear tracking pipe.",
 "Inconsistently tagged tokens enter; the pipe branches and tokens flow into the wrong channels.",
 "A lazy-river ride with channels that split and mislabel every floating token.",
 "Silted, overgrown channels crisscross a delta; a lime sluice gate reroutes tokens into one channel."),
("Midnight scheduled post", "Agency & client work",
 "A small posting queue feeding a publishing slot, a timer dial on top.",
 "The dial slips; posts fire out of the slot into a darkened overnight room.",
 "A cuckoo-clock funhouse where posts pop out of doors at random hours.",
 "A fallen cuckoo clock in a dark landscape; a lime dial is set and the first door closes."),

# --- Process & approvals ---------------------------------------------------
("Everything is urgent", "Process & approvals",
 "A row of task cards on a desk; one carries a small lime flag.",
 "Flags are added to every card, then flags to the flags, until the work disappears under them.",
 "A fun-house facade entirely covered in flags, the entrance lost among them.",
 "A flag-strewn ruin at landscape scale; a lime sorting rack raises only the few flags that matter."),
("Got a sec?", "Process & approvals",
 "A focus block sitting on a small desk platform.",
 "Tapping arms nudge the block off its platform again and again; each time it lands further away.",
 "A dunk-tank booth that keeps dropping the focus block into a tank.",
 "A cracked dunk tank in a flooded ruin; a lime shield holds the block on its platform."),
("Context switching", "Process & approvals",
 "Six task trays arranged around a small rotating desk.",
 "The desk spins between trays faster and faster; each task is started and abandoned half-done.",
 "A tilt-a-whirl flinging a work car between six task trays.",
 "A seized tilt-a-whirl among half-finished tasks; a lime brake locks the desk facing one tray."),
("Blocked by another team", "Process & approvals",
 "Two conveyor lines meeting at a single graphite gate.",
 "The gate stays shut; work piles up on the waiting line and spills over the rails.",
 "A roller coaster stalled on its lift hill, its cars backed up down the track.",
 "A rusted lift hill with piled cars; a lime chain drive restarts the climb."),
("Duplicate work", "Process & approvals",
 "Two identical workbenches side by side, each building the same part.",
 "Identical parts pile up on both benches, neither aware of the other.",
 "A twin racing coaster where two identical trains carry the same parts side by side.",
 "Twin wrecks lie side by side; a lime merge track combines them into one line."),
("Single point of knowledge", "Process & approvals",
 "A small vault with one graphite key module slotted into its door.",
 "The key module is removed; everything that needs the vault queues at the door.",
 "A keymaster carnival game: one key, a wall of locks.",
 "A sealed vault ruin surrounded by queued work; a lime rig duplicates the key."),
("Vague ticket", "Process & approvals",
 "A blank ticket card in an intake tray.",
 "Clarification loops orbit the card and multiply until the tray is ringed with them.",
 "An orbiter ride circling a blank card on long frosted arms.",
 "A seized orbiter above a crater; a lime arm stamps a clear diagram onto the card."),
("Purchase order relay", "Process & approvals",
 "A purchase-order form on a tray with three signature slots.",
 "More slots appear across departments; the form travels tray to tray and never returns.",
 "A relay-race track where a baton-shaped form is passed between mechanical stations.",
 "A ruined track littered with forms; a lime baton carries one form across the finish."),
("Signature chase", "Process & approvals",
 "A document on a small rail cart with signature stops along the route.",
 "The cart stalls at each stop; a queue of carts builds behind it.",
 "A carnival train that stops at every station and never finishes the loop.",
 "A derailed train in a ruin; a lime bypass track skips the stalled stops."),
("Net-90 invoice", "Process & approvals",
 "An invoice envelope resting in a waiting tray.",
 "Reminder envelopes pile on top; the tray sinks under the weight.",
 "A slow snail-race attraction where invoice envelopes creep along lanes.",
 "A frozen racetrack buried in reminders; a lime conveyor moves the first invoice across the line."),

# --- Office physical -------------------------------------------------------
("Thermostat war", "Office physical",
 "One thermostat dial on a miniature office wall above a row of desks.",
 "The dial swings back and forth; frost creeps over some desks while others shimmer with heat.",
 "A hot-and-cold spinning ride whose arms alternate frosted and heat-glowing gondolas.",
 "A cracked plain, half frozen and half scorched; a lime regulator balances the zones."),
("Kitchen mug tower", "Office physical",
 "One unwashed mug left in a small ivory office-kitchen sink.",
 "Mugs are stacked on the first one, rim on rim, until a leaning tower rises out of the sink and over the counter.",
 "A spinning teacup ride built from the stacked mugs, each cup wobbling on the one beneath it.",
 "A landscape of mug shards around a toppled ride hub; a lime rack is sorting out the few intact mugs."),
("Hot-desk shuffle", "Office physical",
 "One desk with a lime booking tag and a small, tidy set of belongings.",
 "Desks slide into new positions on floor rails; belongings are left behind and scatter across the aisles.",
 "A shell-game attraction where desks slide under giant frosted cups and are swapped around.",
 "Desks scattered across a cracked plain; a lime floor grid is laid down and assigns each one a place."),
("Dead whiteboard marker", "Office physical",
 "A whiteboard with one faint, streaky stroke and a marker tray below.",
 "Each dead marker is dropped back into the tray and a new one tried, until they spill onto the floor.",
 "A dart booth where every dart is a dry marker bouncing off a blank board.",
 "A drift of dead markers below a toppled whiteboard; a lime refill station starts filling the first one."),
("Empty supply closet", "Office physical",
 "A supply shelf with one sticky-note pad left on it.",
 "The shelf empties and small hoards of supplies form on desks around the closet.",
 "A prize booth with bare shelves and a queue of empty baskets.",
 "Collapsed shelving in a quiet ruin; a lime conveyor restocks the first shelf."),
("Mailroom parcel pile", "Office physical",
 "A single parcel on a clean mailroom counter.",
 "Parcels arrive faster than they are sorted, stacking until the mailroom walls bow outward.",
 "A helter-skelter slide that parcels ride down in a spiral, landing in a heap.",
 "A parcel landslide filling a valley; a lime sorting chute routes them into lanes."),
("Badge reader standoff", "Office physical",
 "A small badge reader beside a frosted glass door.",
 "The reader rejects every badge; a queue of badges on lanyards stacks up at the door.",
 "A gravitron ride pinning badges to its spinning walls.",
 "A collapsed door frame in badge rubble; a lime reader lights and the gate opens."),
("Projector aspect mismatch", "Office physical",
 "A projector casting a slightly cropped image onto a small screen.",
 "The crop worsens and content spills off the screen onto the walls and ceiling.",
 "A parachute-drop tower whose canopy is a projection screen showing mismatched frames.",
 "A torn canopy across a ruin; a lime frame resets the image to fit."),
("Shredder jam", "Office physical",
 "A small shredder with one sheet feeding into its mouth.",
 "The shredder jams and shreds erupt from every seam.",
 "A cotton-candy machine spinning paper shreds into huge clouds.",
 "Shred drifts across a plain; a lime compactor bales them."),
("Sticky-note wall collapse", "Office physical",
 "A wall with a few square notes in neat rows.",
 "Notes are layered on notes until their weight peels the whole stack off the wall.",
 "A climbing wall built from paper notes, holds peeling off as it's climbed by the next layer.",
 "A fallen wall of notes like a scree slope; a lime frame re-hangs them in order."),

# --- Reporting & admin -----------------------------------------------------
("Report nobody reads", "Reporting & admin",
 "A bound report on a delivery tray outside a closed door.",
 "Reports keep arriving on schedule; unread stacks rise beside the door.",
 "A dark ride whose cars glide through canyons of unread reports.",
 "Unread stacks form a canyon; a lime reader arm lifts one page to the light."),
("Mandatory training module", "Reporting & admin",
 "A training cartridge slotted into a laptop.",
 "New policy cartridges queue behind it; progress resets each time one is added.",
 "An obstacle-course attraction with the same hurdle repeated around every bend.",
 "A ruined obstacle course; a lime track cuts straight across it."),
("Survey fatigue", "Reporting & admin",
 "A single survey card in an inbox tray.",
 "Survey cards pile up faster than they're answered, most of them blank.",
 "A plinko board raining blank survey cards into bins.",
 "A plinko ruin buried in blank cards; a lime collector gathers the few answered ones."),
("Review form maze", "Reporting & admin",
 "A short performance form with a handful of boxes.",
 "Boxes multiply across new pages until the form is a stack of grids.",
 "A mirror maze made of form boxes.",
 "A box-strewn maze ruin; a lime path marks the way through."),
("Reorg shuffle", "Reporting & admin",
 "An org chart of frosted acrylic blocks linked by lime rods.",
 "The blocks reshuffle again and again; rods snap and hang loose.",
 "A scrambler ride flinging org blocks between arms.",
 "Toppled blocks across a wide plain; a lime frame rebuilds a simple chart."),
("Budget reallocation", "Reporting & admin",
 "Budget tokens in colour-banded bins on a desk.",
 "Tokens are shifted between bins until none of them balance and some overflow.",
 "A water-wheel attraction sloshing tokens from bucket to bucket.",
 "A dry, seized water wheel; a lime balancing beam levels the bins."),
("Vendor onboarding forms", "Reporting & admin",
 "A thin vendor form packet on a clipboard.",
 "Forms multiply into a tall, leaning stack.",
 "A paper-plane launch booth sending forms in every direction.",
 "A dune of forms; a lime binder clamps them into one packet."),
("Tool migration", "Reporting & admin",
 "An old graphite system block beside a new frosted one, joined by a transfer bridge.",
 "The bridge sags mid-transfer and data blocks fall between the systems.",
 "A rope-bridge ride swaying between two platforms.",
 "A collapsed bridge over a gorge full of data blocks; a lime span reconnects the platforms."),
("Stale wiki", "Reporting & admin",
 "A shelf of ivory binders with a few dusty spines.",
 "Binders yellow and contradict each other; the shelf sags.",
 "A haunted-house dark ride through dusty binder corridors.",
 "A collapsed library ruin; a lime rack re-indexes the current pages."),
("Search finds nothing", "Reporting & admin",
 "A card-catalog drawer with a search probe hovering over it.",
 "The probe opens the wrong drawers and spills cards everywhere.",
 "A claw game that grabs the wrong card every time.",
 "A spilled catalog ruin; a lime index rail sorts the cards."),

# --- Launch & web ----------------------------------------------------------
("Broken link", "Launch & web",
 "A chain of page tiles connected by lime links.",
 "One link breaks; everything travelling down the chain falls through the gap.",
 "A monorail with a missing section of track.",
 "A monorail ruin spanning a chasm; a lime section is lowered into the gap."),
("Cache not cleared", "Launch & web",
 "A display case showing an older page model while a new one waits beside it.",
 "New versions stack behind the glass, but the old one stays in front.",
 "A carnival diorama window stuck on the same old scene.",
 "A dusty display ruin; a lime wiper clears the glass."),
("Works on my machine", "Launch & web",
 "A working mechanism on one desk rig.",
 "The mechanism moves to a second desk and falls apart piece by piece.",
 "A trapeze rig that works from one platform and fails from the other.",
 "A collapsed trapeze between two towers; a lime platform matches both sides."),
("Placeholder shipped", "Launch & web",
 "A layout block of grey placeholder bars on a conveyor.",
 "Placeholder blocks ship out on the conveyor into the world.",
 "A carnival train delivering grey blocks to every booth.",
 "Grey blocks across a ruin; a lime stamp replaces them one by one."),
("Heavy page", "Launch & web",
 "A page tile carrying oversized image slabs.",
 "The page bows under the weight and slows to a crawl.",
 "A strongman lift attraction straining under image slabs.",
 "A crushed page ruin; a lime compressor lightens the slabs."),
("Form to nowhere", "Launch & web",
 "A form slot on a web page model feeding into a pipe.",
 "Submissions drop into the pipe, which leads nowhere.",
 "A water slide that ends in thin air.",
 "Submissions pooled at the slide's broken end; a lime pipe reroutes them."),
("Staging vs production", "Launch & web",
 "Two identical platforms, one marked with a lime band.",
 "Changes are pushed to the wrong platform.",
 "A mirror-image twin roller coaster.",
 "Twin ruins; a lime marker picks out production."),
("Friday hotfix", "Launch & web",
 "A small patch plate over a crack.",
 "The patch cracks further and more patches are bolted over it.",
 "A bobsled track patched mid-run.",
 "A patchwork ruin; a lime brace spans the crack."),
("QA ticket bounce", "Launch & web",
 "A ticket between a build tray and a QA tray.",
 "The ticket bounces between them, collecting stamps.",
 "A trampoline that keeps bouncing the ticket.",
 "A torn trampoline; a lime catch holds the ticket."),
("Sprint carryover", "Launch & web",
 "A sprint tray of task cards.",
 "Unfinished cards carry over and pile into the next tray.",
 "A kiddie-train ride hauling carryover cards.",
 "A derailed train; a lime sorter clears the cards."),
]
